apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-deployment
  labels:
    app: todo-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
      - name: todo-api-container
        image: todo-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-password
          - name: ADMIN_DB_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-admin-user
          - name: ADMIN_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-admin-password
          - name: API_HOST
            valueFrom:
              configMapKeyRef:
                name: todo-api-config
                key: api-host
          - name: API_PORT
            valueFrom:
              configMapKeyRef:
                name: todo-api-config
                key: api-port
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres-url
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: "todo_api_database"
          - name: SEED_DB
            value: "true"
          - name: ADMIN_DB_NAME
            value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: todo-api-service
spec:
  type: NodePort
  selector:
    app: todo-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
