apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  labels:
    app: web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: todo-web-app-container
        image: todo-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
          - name: API_HOST
            value: 'localhost'
          - name: API_PORT
            value: '30080'
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
